services:
  app:
    image: lscr.io/linuxserver/nginx:latest
    volumes:
      - ./php/index.php:/config/www/index.php
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:80

  db:
    image: mariadb
    env_file:
      - .env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306 
    links:
      - db