name: Build and Deploy a php app
on: workflow_dispatch
jobs:
  Build-and-deploy:
    runs-on: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: build and deploy
      run: docker compose up --build --detach
  Test:
    runs-on: linux
    needs: Build-and-deploy
    steps:
    - name: test
      run: sleep 10 && docker compose exec app curl http://localhost
  Purge:
    runs-on: linux
    needs: [Build-and-deploy, Test]
    steps:
    - name: Stop
      run: docker compose stop
