name: Build and Deploy a php app
on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Deploy
      run: docker compose up --build --detach
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: http://localhost:8080/index.php
        destination: screenshot.png
    - name: Stop
      run: docker compose stop
