name: Build and Deploy a php app
on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: linux
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Deploy
      run: |
        docker compose up --build --detach
        docker compose exec app curl http://localhost
    - name: Stop
      run: docker compose stop
